[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "run-llm-locally"
version = "0.1.0"
description = "General-purpose Hugging Face model runner supporting both text-only and multi-modal models"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "AI Assistant"}]
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.35.0",
    "Pillow>=10.0.0",
    "accelerate>=0.20.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]